### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jibaku** [Nordgedanken/IMAPServer-rs#12]
Hello, using `cargo install IMAPServer-rs`does not seems to work:

```
~ ❯❯❯ cargo install IMAPServer-rs                                                                                                                                                  ⏎
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: could not find `IMAPServer-rs` in registry `https://github.com/rust-lang/crates.io-index`
```

Should I update the README to tell people to use `git clone` / `cargo build` ?

**Comment by MTRNord** [comment]
This repo isnt really maintained currently :/ I currently have no time to work on it but yes I guess i should Update the readme

**Comment by MTRNord** [comment]
d298af4d40c277bf8e4a9f9eaa8dc22b07c51021  <--- The Readme also now mentions that I am not activly maintaining it currently and Updates might happen late/bugs may come up unexpected

**Comment by MTRNord** [comment]
@jibaku about the cargo issue: I think when I published it is was first a Name saving. Not yet a fully featured version (which the current git isn't either^^)
